### ISSUE TITLE
Error when batch converting

### ISSUE THREAD

**Issue by f6v** [cloudconvert/cloudconvert-cli#2]
I'm running batch convert to pdf but always get following error:

```
 if (fn === null) throw new Error("Callback was already called.");---------------] 0%  Starting...
                             ^  ->  pdf  [--------------------------------------------------] 0%  Starting...
Starting...
Error: Callback was already called.
    at /usr/local/lib/node_modules/cloudconvert-cli/node_modules/async/lib/async.js:43:36
    at /usr/local/lib/node_modules/cloudconvert-cli/node_modules/async/lib/async.js:358:17
    at Process.<anonymous> (/usr/local/lib/node_modules/cloudconvert-cli/lib/cli.js:50:13)
    at emitOne (events.js:115:13)
    at Process.emit (events.js:210:7)
    at /usr/local/lib/node_modules/cloudconvert-cli/node_modules/cloudconvert/lib/api.js:193:41
    at /usr/local/lib/node_modules/cloudconvert-cli/node_modules/cloudconvert/lib/process.js:269:17
    at /usr/local/lib/node_modules/cloudconvert-cli/node_modules/cloudconvert/lib/process.js:138:17
    at Request._callback (/usr/local/lib/node_modules/cloudconvert-cli/node_modules/cloudconvert/lib/api.js:46:17)
    at Request.self.callback (/usr/local/lib/node_modules/cloudconvert-cli/node_modules/request/request.js:188:22)
```
Node version: v8.1.3

What could the issue be?

**Comment by josiasmontag** [comment]
Might be related to https://github.com/cloudconvert/cloudconvert-node/issues/14
Can you try if it is resolved after updating using `npm install -g cloudconvert-cli`?

**Comment by f6v** [comment]
@josiasmontag thanks for your response! I've updated, but still getting it.
