### ISSUE TITLE
this.stream.clearLine is not a function

### ISSUE THREAD

**Issue by zbacsi** [cloudconvert/cloudconvert-cli#6]
Running from command line everything works fine. But from a script it fails:

node_modules/cloudconvert-cli/lib/multibar.js:43
        this.stream.clearLine();
                    ^
`TypeError: this.stream.clearLine is not a function
    at Multibar.terminate (node_modules/cloudconvert-cli/lib/multibar.js:43:21)
    at ProgressBar.bar.terminate (node_modules/cloudconvert-cli/lib/multibar.js:34:22)
    at ProgressBar.tick (node_modules/cloudconvert-cli/node_modules/progress/lib/node-progress.js:103:10)
    at Multibar.tick (node_modules/cloudconvert-cli/lib/multibar.js:57:17)
    at ProgressBar.bar.tick (node_modules/cloudconvert-cli/lib/multibar.js:29:18)
    at ProgressBar.update (node_modules/cloudconvert-cli/node_modules/progress/lib/node-progress.js:199:8)
    at Process.<anonymous> (node_modules/cloudconvert-cli/lib/cli.js:56:17)
    at Process.emit (events.js:189:13)
    at node_modules/cloudconvert-cli/node_modules/cloudconvert/lib/process.js:442:22
    at node_modules/cloudconvert-cli/node_modules/cloudconvert/node_modules/async/dist/async.js:473:16`

**Comment by taoxiaojie** [comment]
I hava the same  problem.
