### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by devrosx** [cloudconvert/cloudconvert-cli#7]
Hello updated to macosx Mojave (used cloudconvert before without problems) updated script to latest version and have this error with any file

any idea what could be wrong, im using API V2 key

`⠇ Downloading PRI_DLBT1810589EN02.pdf(node:2245) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/local/lib/node_modules/cloudconvert-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/cloudconvert-cli/node_modules/axios/lib/core/settle.js:17:12)`

thanks Jan

**Comment by josiasmontag** [comment]
There was a bug when downloading the output files. The just published version `2.0.1` fixes this.

**Comment by devrosx** [comment]
thanks it works now 👍
